spring.application.name=student-management-system

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Logging
logging.level.root=INFO
logging.level.com.kodewala.sms=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

logging.file.name=logs/student-management-system.log

# HikariCP connection pool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Initial Admin User
app.admin.username=${APP_ADMIN_USERNAME:}
app.admin.password=${APP_ADMIN_PASSWORD:}

# Initial User
app.user.username=${APP_USER_USERNAME:}
app.user.password=${APP_USER_PASSWORD:}

#Flyway
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true
spring.flyway.out-of-order=false

spring.profiles.active=dev
server.port=8080